feat:delete dairy
tigerscave/tigers-diary pull request #17
Opened 2023-12-16 11:17 UTC by mre1ght

#15 
### Done
After pushing each delete-icon ,Google spread sheets data is deleted.

 ### Not yet
Also the data on the HTML is deleted.
Display alert modal ,before Deleting the data.

2023-12-20 09:40 UTC, mre1ght commented
### Done
After clicking the delete icon, both the data in Google Sheets and the corresponding data in the HTML are successfully deleted.(Except during name filtering)

![スクリーンショット 2023-12-20 18 35 05](https://github.com/tigerscave/tigers-diary/assets/129372334/b1828945-400a-49b1-8579-e6b7a39b5ede)

2023-12-21 05:10 UTC, azamiya requested changes

2023-12-21 05:10 UTC, azamiya commented on index.html
> +        <th class="border" style="width: 30rem;">Diary</th>
tailwind使う

2023-12-21 05:28 UTC, mre1ght commented on index.html
> +        <th class="border" style="width: 30rem;">Diary</th>
ありがとうございます。修正しました。

2023-12-21 05:30 UTC, merged